apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-security
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ozair-17/Orbit-Platform
    targetRevision: main
    path: platform/security
  destination:
    server: https://kubernetes.default.svc
    namespace: platform-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true