apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-service-mesh
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/Ozair-17/Orbit-Platform
    targetRevision: main
    path: Orbit-Platform/platform/service-mesh

  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
  
    syncOptions:
      - CreateNamespace=true