apiVersion: security.istio.io/v1
kind: PeerAuthentication
metadata:
  name: orbit-api-mtls
  namespace: platform-dev
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: orbit-api
  mtls:
    mode: STRICT
  portLevelMtls:
    8080:
      mode: DISABLE