apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: platform-dev
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: orbit-api
  policyTypes:
    - Ingress
    