apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: orbit-api-readonly
  namespace: platform-dev
rules:
  - apiGroups: [""]
    resources: ["pods","services","configmaps","endpoints"]
    verbs: ["get","list","watch"]
