apiVersion: v1
kind: ConfigMap
metadata:
  name: orbit-worker-config
  namespace: {{ .Values.namespace}}
data:
  APP_NAME: {{ .Values.config.appName | quote}}
  MESSAGE: {{ .Values.config.message | quote}}
