apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbit-worker
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: orbit-worker
    app.kubernetes.io/instance: dev
    app.kubernetes.io/component: backend
    app.kubernetes.io/part-of: orbit-platform
    app.kubernetes.io/managed-by: Helm
    orbit.dev/environment: dev
    version: v1
spec:
  replicas: {{ .Values.replicaCount }}
  revisionHistoryLimit: 3

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app.kubernetes.io/name: orbit-worker
      app.kubernetes.io/instance: dev

  template:
    metadata:
      labels:
        app.kubernetes.io/name: orbit-worker
        app.kubernetes.io/instance: dev
        app.kubernetes.io/component: backend
        app.kubernetes.io/part-of: orbit-platform
        app.kubernetes.io/managed-by: Helm
        orbit.dev/environment: dev
        version: v1

    spec:
      serviceAccountName: orbit-worker
      containers:
        - name: orbit-worker
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}

          envFrom:
            - configMapRef:
                name: orbit-worker-config

            - secretRef:
                name: orbit-worker-secret

          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}

          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
          