apiVersion: v1
kind: Service
metadata:
  name: orbit-worker
  namespace: {{ .Values.namespace}}
  labels:
    app.kubernetes.io/name: orbit-worker
    app.kubernetes.io/instance: dev
spec:
  type: {{ .Values.service.type}}
  selector:
    app.kubernetes.io/name: orbit-worker
    app.kubernetes.io/instance: dev
  ports:
    - name: http
      port: {{ .Values.service.port}}
      targetPort: {{ .Values.service.targetPort}}    