apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: orbit-api-readonly
  namespace: platform-dev
subjects:
  - kind: ServiceAccount
    name: orbit-api
    namespace: platform-dev
roleRef:
  kind: Role
  name: orbit-api-readonly
  apiGroup: rbac.authorization.k8s.io